# -*- coding: utf-8 -*-
"""Salinan dari RAG Gemini - AVPN IT Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WNaZG_9EWftMY5J_gfnWlfSEtKbgJfn

# RAG (Retrieval-Augmented Generation) dengan Gemini & ChromaDB

## Apa itu RAG?

LLM seperti Gemini punya keterbatasan: pengetahuannya hanya sampai tanggal training-nya.
Mereka tidak tahu tentang:
- Dokumen internal yang belum pernah dipublikasikan
- Data terbaru setelah cutoff date
- Informasi spesifik yang tidak ada di internet

**RAG** adalah teknik yang menggabungkan kemampuan LLM dengan pencarian dokumen.
Alih-alih mengandalkan "memori" model, kita ambil informasi yang relevan dari database dulu,
lalu dikirim ke model sebagai konteks tambahan.

### Arsitektur RAG di notebook ini

```
Dokumen PDF (Pearson VUE AI Certification)
         ↓
    Document Loader      ← baca halaman per halaman
         ↓
      Chunking           ← potong jadi bagian kecil
         ↓
      Embedding          ← ubah teks jadi vector angka
         ↓
     ChromaDB            ← simpan vector di database
         ↓
  User tanya sesuatu
         ↓
      Retriever          ← cari chunk paling relevan
         ↓
    Prompt Template      ← gabungkan konteks + pertanyaan
         ↓
   Gemini (LLM)          ← generate jawaban
         ↓
      Jawaban
```

### Dokumen yang digunakan

Notebook ini menggunakan dokumen **IT Specialist: Artificial Intelligence** dari **Pearson VUE** —
sebuah exam objective guide yang menjelaskan topik-topik yang diujikan dalam sertifikasi AI mereka.
Kita akan membangun RAG yang bisa menjawab pertanyaan tentang isi dokumen ini.

## Instalasi Library

Package yang kita butuhkan:
- `google-generativeai` — SDK resmi Google untuk Gemini API
- `langchain` & `langchain-google-genai` — framework RAG + integrasi Gemini
- `langchain_community` — berisi connector ke ChromaDB dan document loaders
- `pypdf` — membaca file PDF
- `chromadb` — vector database yang akan kita gunakan untuk menyimpan embedding
"""

!pip install -q -U google-generativeai

!pip install -U -q google-generativeai langchain langchain-google-genai langchain_community pypdf chromadb

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from IPython.display import Markdown as md

import warnings
warnings.filterwarnings('ignore')

from google.colab import userdata

"""## Konfigurasi API Key & Model

Kita perlu dua hal sebelum mulai:

### 1. Google AI API Key (untuk Gemini & Embedding)

Cara mendapatkan:
1. Buka [https://aistudio.google.com](https://aistudio.google.com)
2. Klik **Get API Key** → **Create API Key**
3. Di Google Colab: klik ikon 🔑 (Secrets) di sidebar kiri → tambahkan secret `GEMINI`

### 2. Model yang digunakan

- **Gemini 2.5 Flash Lite** — model LLM ringan dari Google, digunakan untuk generate jawaban akhir
- **gemini-embedding-2** — model embedding dari Google, mengubah teks menjadi vector

> Model dan API key cukup dikonfigurasi sekali di sini dan akan dipakai di seluruh notebook.

"""

import google.generativeai as genai

GEMINI = userdata.get('GEMINI')
api_key = GEMINI
genai.configure(api_key=api_key)

chat_model = ChatGoogleGenerativeAI(google_api_key=GEMINI,
                                   model="gemini-2.5-flash-lite")

"""## Load Dokumen PDF

Sebelum membangun RAG, kita perlu dokumen sumber yang akan jadi "pengetahuan" model.

Kita download PDF exam objectives dari Pearson VUE menggunakan `curl`,
lalu membacanya dengan `PyPDFLoader` dari LangChain.

`PyPDFLoader` secara otomatis:
- Membaca setiap halaman PDF
- Mengekstrak teksnya
- Membungkusnya sebagai objek `Document` dengan metadata halaman

> `load_and_split()` = load dokumen sekaligus split per halaman.
> Hasilnya adalah list of `Document`, satu item per halaman PDF.

"""

# download pdf dengan curl
!curl -o  ai_pv.pdf https://www.pearsonvue.com/content/dam/VUE/vue/en/documents/clients/it-specialist/its-od-307-artificial-intel-pearson.pdf

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("ai_pv.pdf")
pages = loader.load_and_split()

"""Kita cek isi halaman pertama dan total halaman untuk memastikan PDF berhasil dibaca."""

pages[0].page_content

len(pages)

"""# Chunking — Memotong Dokumen Jadi Bagian Kecil

## Mengapa perlu Chunking?

LLM punya batas token — kita tidak bisa mengirim seluruh isi dokumen sekaligus.
Selain itu, mengirim seluruh dokumen ke model itu tidak efisien dan mahal.

Dengan chunking, dokumen dipotong jadi potongan-potongan kecil (chunk).
Saat user bertanya, kita hanya ambil chunk yang **paling relevan** dengan pertanyaan tersebut —
bukan keseluruhan dokumen.

## NLTKTextSplitter

Berbeda dengan splitter berbasis karakter biasa, **NLTKTextSplitter** memotong teks
berdasarkan **batas kalimat** menggunakan Natural Language Toolkit (NLTK).
Ini menghasilkan chunk yang lebih natural karena tidak memotong di tengah kalimat.

**Parameter penting:**
- `chunk_size` — maksimal panjang karakter per chunk. Terlalu kecil = konteks kurang, terlalu besar = tidak efisien
- `chunk_overlap` — berapa karakter dari akhir chunk sebelumnya yang diulang di awal chunk berikutnya,
  agar informasi di batas potongan tidak hilang

> NLTK perlu mendownload tokenizer `punkt_tab` terlebih dahulu sebelum bisa digunakan.

"""

import nltk
nltk.download('punkt_tab')

"""### Demo Chunking dengan Teks Sederhana

Sebelum diterapkan ke dokumen PDF, kita coba dulu dengan teks pendek
agar lebih mudah melihat bagaimana chunking bekerja.
"""

from langchain_text_splitters import NLTKTextSplitter

# Misalkan kamu memiliki dokumen seperti berikut
simple_doc = """halo nama saya sardi irfansyah, saya lahir di jakarta. Saya irfan. tinggal di Jakarta."""
print('panjang total karakter:',len(simple_doc),'\n')
# Membuat objek NLTKTextSplitter dengan ukuran chunk dan overlap
text_splitter = NLTKTextSplitter(separator='\n\n',chunk_size=67, chunk_overlap=10) #default separator='\n\n'

# Memecah dokumen menjadi beberapa chunk
chunks = text_splitter.split_text(simple_doc)
print(chunks,'\n')

# Menampilkan hasil chunk
for i, chunk in enumerate(chunks):
    #panjang karakter
    print(f"Panjang chunk {i+1}: {len(chunk)} karakter")
    print(f"Chunk {i+1}:")
    print(chunk)
    print("-" * 50)

"""Penjelasan:
- Dapat kita lihat bahwa `NLTKTextSplitter` akan mencoba membuat text tersebut dipisahkan berdasarkan kalimat atau tanda `titik`. Jadi setiap ada titik maka akan dibuat chunk.
- Ketika panjang karakter lebih dari `chunk_size`, ini akan mengakibatkan peringatan warning.
- `chunk_overlap` digunakan untuk menentukan jumlah karakter yang harus tumpang tindih antara chunk yang berdekatan.

Jika anda ingin melihat ilustrasi tentang konfigurasi chunk, anda dapat melihatnya [di sini](https://dev.to/peterabel/what-chunk-size-and-chunk-overlap-should-you-use-4338).

### Terapkan Chunking ke Dokumen PDF

Sekarang kita terapkan splitter yang sama ke dokumen Pearson VUE yang sudah kita load.
Kita pakai `chunk_size=500` dan `chunk_overlap=100` sebagai trade-off antara
konteks yang cukup dan efisiensi pencarian.
"""

from langchain_text_splitters import NLTKTextSplitter

text_splitter = NLTKTextSplitter(chunk_size=500, chunk_overlap=100)

chunks = text_splitter.split_documents(pages)

print(len(chunks))

print(type(chunks[0]))

# Mengecek hasil pemecahan menjadi chunk
print(f"Jumlah chunks yang dihasilkan: {len(chunks)}")
print(f"Tipe data chunk pertama: {type(chunks[0])}")

"""Kita lihat isi chunk pertama untuk memverifikasi hasil potongan."""

# Menampilkan chunk pertama
# panjang chunk
print(f"Panjang chunk pertama: {len(chunks[0].page_content)} karakter")
print("\nContoh chunk pertama:")
print(chunks[0].page_content)  # Memastikan bahwa setiap chunk memiliki konten

"""# Embedding — Mengubah Teks Menjadi Vector

## Apa itu Embedding?

Embedding adalah proses mengubah teks menjadi **deretan angka (vector)**
yang merepresentasikan makna dari teks tersebut.

```
"Apa skill yang dibutuhkan untuk sertifikasi AI?"  →  [0.12, -0.34, 0.87, ...]  (768 angka)
"Keterampilan apa yang perlu dikuasai untuk ujian AI?"  →  [0.11, -0.32, 0.85, ...]  (mirip!)
"Harga saham Tokopedia hari ini"  →  [-0.55, 0.22, -0.14, ...]  (jauh berbeda)
```

Teks yang maknanya **mirip** akan menghasilkan vector yang **berdekatan** di ruang vektor.
Ini yang memungkinkan pencarian semantik — mencari berdasarkan makna, bukan hanya kata kunci.

## Model Embedding yang Digunakan

`gemini-embedding-2` adalah model embedding dari Google yang menghasilkan vector berdimensi 768.
Kita set `output_dimensionality=768` untuk menyesuaikan dimensi dengan konfigurasi vector store.

> Proses embedding ini akan dijalankan untuk **setiap chunk** saat menyimpan ke ChromaDB,
> dan juga untuk **setiap pertanyaan** user saat melakukan pencarian.

"""

from langchain_google_genai import GoogleGenerativeAIEmbeddings

embedding_model = GoogleGenerativeAIEmbeddings(google_api_key=api_key, model="gemini-embedding-2", output_dimensionality=768)

"""# Vector Database — ChromaDB

## Apa itu Vector Database?

Vector database adalah database yang dirancang khusus untuk menyimpan dan mencari vector secara efisien.
Berbeda dengan database biasa yang mencari berdasarkan nilai eksak, vector database mencari
berdasarkan **kemiripan** (similarity) antar vector.

## ChromaDB

**ChromaDB** adalah vector database open-source yang bisa berjalan langsung di memori
atau disimpan ke disk. Di notebook ini kita pakai mode `persist_directory` agar
data tidak hilang setelah runtime Colab restart.

### Alur penyimpanan:

```
chunks (list of Document)
        ↓
  embedding_model.embed()    ← setiap chunk diubah jadi vector
        ↓
   ChromaDB.from_documents() ← vector + teks disimpan di ChromaDB
        ↓
   persist_directory="./chroma_db_"  ← disimpan ke disk
```

> `Chroma.from_documents()` melakukan dua hal sekaligus: embedding dan penyimpanan.
> Kita tidak perlu memanggil embed secara manual.

Dokumentasi vector store: [python.langchain.com/docs/how_to/vectorstore_retriever](https://python.langchain.com/docs/how_to/vectorstore_retriever/)

"""

from langchain_community.vectorstores import Chroma

# Sematkan setiap chunk dan muat ke dalam chromadb
db = Chroma.from_documents(chunks, embedding_model, persist_directory="./chroma_db_")

# Menyimpan perubahan ke disk
db.persist()

"""### Membuka Koneksi ke ChromaDB yang Sudah Tersimpan

Setelah data disimpan, kita buka koneksi baru ke database yang sama.
Ini memisahkan proses **penulisan** (from_documents) dan **pembacaan** (koneksi retriever),
yang penting untuk skenario production di mana embedding hanya dilakukan sekali.
"""

# mengatur koneksi untuk menghubungkan ke ChromaDB
db_connection = Chroma(persist_directory="./chroma_db_", embedding_function=embedding_model)

"""### Membuat Retriever

**Retriever** adalah objek yang tugasnya satu: menerima pertanyaan dan mengembalikan
dokumen-dokumen yang paling relevan dari vector database.

Di balik layar, retriever:
1. Mengubah pertanyaan user menjadi vector (embedding)
2. Mencari vector yang paling mirip di ChromaDB (similarity search)
3. Mengembalikan dokumen-dokumen dengan similarity tertinggi
"""

# Mengonversi koneksi Chroma menjadi objek retriever untuk pencarian dokumen berbasis vektor
retriever = db_connection.as_retriever(search_kwargs={"k": 10})

print(type(retriever))

"""`k` adalah parameter yang digunakan dalam fungsi as_retriever() untuk menentukan jumlah hasil pencarian teratas (top-k) yang akan diambil dari basis data vektor (Chroma database).

Parameter ini digunakan dalam proses pencarian dokumen relevan yang mengacu pada jumlah dokumen atau chunk yang akan diambil dari kumpulan dokumen yang lebih besar (misalnya, dari Chroma vector store) berdasarkan kesamaan atau kedekatannya dengan pertanyaan yang diajukan.

> Nilai k umumnya lebih kecil dari total chunk.

### Uji Coba Retriever

Sebelum membangun RAG chain, kita test dulu retriever-nya secara langsung.
Kita kirim pertanyaan dan lihat dokumen apa yang dikembalikan.
"""

check_response = retriever.invoke("jelaskan skill yang dibutuhkan untuk sertifikasi pearson vue dalam bidang AI?")
len(check_response)

"""Tampilkan isi chunk pertama yang dikembalikan retriever:"""

md(check_response[0].page_content)

"""# Prompt Template

## Mengapa Perlu Template?

Kita tidak bisa langsung mengirim pertanyaan user ke LLM begitu saja.
LLM perlu **konteks** (dokumen yang sudah diambil retriever) beserta **instruksi** yang jelas.

Prompt template memungkinkan kita mendefinisikan struktur pesan secara konsisten,
dengan placeholder `{context}` dan `{question}` yang diisi secara otomatis saat runtime.

## Komponen Template di Notebook Ini

**SystemMessage** — instruksi tetap yang diberikan ke model di awal, mendefinisikan perannya:
```
"Anda adalah AI yang dapat menjawab pertanyaan berdasarkan konteks..."
```

**HumanMessagePromptTemplate** — template pesan dari user, berisi placeholder:
```
Jawab pertanyaan berikut berdasarkan konteks.
konteks: {context}         ← diisi dengan chunk dari ChromaDB
pertanyaan: {question}     ← diisi dengan pertanyaan user
jawaban:
```

Dokumentasi: [python.langchain.com/docs/concepts/prompt_templates](https://python.langchain.com/docs/concepts/prompt_templates/)

"""

from langchain_core.messages import SystemMessage
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate

# Membuat template pesan untuk sistem dan pesan pengguna
chat_template = ChatPromptTemplate.from_messages([
    # System Message Prompt Template
    SystemMessage(content="""Anda adalah AI yang dapat menjawab pertanyaan berdasarkan konteks dan pertanyaan dari user.
                 Anda harus menjawab pertanyaan user, berdasarkan konteks"""),

    # Human Message Prompt Template
    HumanMessagePromptTemplate.from_template("""Jawab pertanyaan berikut berdasarkan konteks.
    konteks: {context}
    pertanyaan: {question}
    jawaban: """)
])

"""### Output Parser & Format Docs

**StrOutputParser** mengubah output LLM (yang berupa objek `AIMessage`) menjadi string biasa
agar lebih mudah ditampilkan.

**`format_docs`** adalah fungsi helper yang menggabungkan semua chunk yang dikembalikan retriever
menjadi satu string panjang, dipisahkan dua baris kosong. String inilah yang dimasukkan
ke placeholder `{context}` di prompt template.
"""

from langchain_core.output_parsers import StrOutputParser

output_parser = StrOutputParser()

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

"""Kita lihat dulu seperti apa output dari `format_docs` sebelum dipakai di chain:"""

# Setelah dokumen diambil oleh retriever dan di-format
formatted_docs = format_docs(chunks)  # Format dokumen yang dihasilkan dari text chunks

# Cetak hasil format
print("Hasil Format Docs:")
print(formatted_docs)  # Menampilkan hasil setelah dokumen diformat

"""## RAG Chain — Menggabungkan Semua Komponen

Inilah bagian utama dari notebook ini. Kita rangkai semua komponen menggunakan
**LCEL (LangChain Expression Language)** dengan operator pipe `|`.

```
{context: retriever | format_docs,   ← ambil dokumen relevan → format jadi string
 question: RunnablePassthrough()}     ← pertanyaan user diteruskan apa adanya
        |
  chat_template                       ← isi placeholder {context} dan {question}
        |
   chat_model                         ← kirim ke Gemini, dapat respons
        |
  output_parser                       ← ubah AIMessage → string biasa
```

**`RunnablePassthrough()`** berarti input (pertanyaan user) diteruskan langsung
tanpa modifikasi ke tahap berikutnya.

Seluruh chain ini bisa dijalankan cukup dengan `.invoke("pertanyaan kamu")`.

"""

from langchain_core.runnables import RunnablePassthrough


rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | chat_template
    | chat_model
    | output_parser
)

"""### Jalankan RAG Chain

Kita test dengan pertanyaan tentang sertifikasi Pearson VUE AI.
Chain akan otomatis: retrieve chunk relevan → format → kirim ke Gemini → return jawaban.
"""

response = rag_chain.invoke("""beritahu saya pemahaman apa yang dibutuhkan untuk sertifikasi IT spesialis: AI dari pearson vue""")

response

"""Tampilkan jawaban dalam format Markdown agar lebih mudah dibaca:"""

md(response)

"""# Contoh Lain: RAG dengan RecursiveCharacterTextSplitter & PromptTemplate

Sejauh ini kita sudah membangun RAG dengan `NLTKTextSplitter` dan `ChatPromptTemplate`.

Sekarang kita lihat **pendekatan alternatif** menggunakan:
- **`RecursiveCharacterTextSplitter`** — splitter berbasis karakter yang lebih umum dipakai
  dan tidak memerlukan NLTK. Memotong secara rekursif dengan berbagai separator (`

`, `
`, ` `)
  dari yang paling besar ke yang paling kecil sampai chunk cukup kecil.
- **`PromptTemplate`** + **`load_qa_chain`** — cara lama (legacy) LangChain untuk membangun QA chain
  sebelum LCEL diperkenalkan. Ditampilkan di sini sebagai perbandingan.

### Perbandingan dengan Pendekatan Sebelumnya

| Aspek | Pendekatan 1 (LCEL) | Pendekatan 2 (Legacy) |
|---|---|---|
| Splitter | NLTKTextSplitter (per kalimat) | RecursiveCharacterTextSplitter (per karakter) |
| Chain | LCEL pipe `\|` | `load_qa_chain` |
| Prompt | `ChatPromptTemplate` | `PromptTemplate` |
| Input PDF | via PyPDFLoader | via PyPDF2 langsung |
| Fleksibilitas | Lebih tinggi, modular | Lebih sederhana untuk pemula |

> **Catatan**: Pendekatan 2 menggunakan style lama LangChain yang sudah deprecated.
> Untuk project baru, gunakan pendekatan LCEL (Pendekatan 1).

"""

# Instalasi dependensi yang dibutuhkan
!pip install -q langchain PyPDF2 #python-dotenv

"""### Import Library

Di sini kita import `PyPDF2` untuk membaca PDF secara manual (tanpa LangChain loader),
dan komponen-komponen legacy LangChain untuk membangun chain.
"""

import os
import io
import PyPDF2
from langchain_classic.prompts import PromptTemplate
from langchain_classic.chains.question_answering import load_qa_chain
from langchain_classic.text_splitter import RecursiveCharacterTextSplitter
from langchain_classic.vectorstores import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
# from dotenv import load_dotenv
from google.colab import files
from IPython.display import Markdown as md

"""### Baca PDF dan Ekstrak Teks

Kita baca file PDF yang sama (`ai_pv.pdf`) menggunakan PyPDF2.
Semua halaman digabungkan menjadi satu string `context`.
"""

# Membuka dan membaca file PDF
with open('/content/ai_pv.pdf', "rb") as file:
    pdf_reader = PyPDF2.PdfReader(file)
    pdf_pages = pdf_reader.pages

    # Mengekstrak teks dari semua halaman
    context = "\n\n".join(page.extract_text() for page in pdf_pages)

"""Cek isi teks yang sudah diekstrak:"""

context

"""### Chunking dengan RecursiveCharacterTextSplitter

`RecursiveCharacterTextSplitter` memotong teks secara rekursif menggunakan beberapa separator
secara berurutan: `\n\n` → `\n` → ` ` → karakter individual.
Ini memastikan potongan selalu bermakna dan tidak terpotong di tengah kata.
"""

# Memecah teks menjadi potongan-potongan kecil
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
texts = text_splitter.split_text(context)

"""Cek jumlah chunks yang dihasilkan dan isi chunk pertama:"""

print(len(texts))

print(type(texts[0]))

texts[0]

"""### Buat Embedding dan Vector Index

Di sini kita langsung membuat ChromaDB in-memory (tanpa `persist_directory`)
dan sekaligus mengonversinya menjadi retriever — semuanya dalam satu baris.
"""

# Membuat embeddings untuk potongan-potongan teks
embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2",google_api_key=api_key)

vector_index = Chroma.from_texts(texts, embeddings).as_retriever(search_kwargs={"k": 20})

"""Cek objek retriever yang dihasilkan:"""

vector_index

print(type(vector_index))

"""### Tanya Jawab Interaktif

Di sini user bisa mengetik pertanyaan secara langsung via `input()`.
Retriever akan mencari dokumen relevan, lalu chain akan menghasilkan jawaban.
"""

# Mendapatkan pertanyaan dari pengguna
user_question = input("Tanyakan pertanyaan: ")

# Mendapatkan dokumen relevan untuk pertanyaan pengguna
docs = vector_index.invoke(user_question)

"""### Buat Prompt, Chain, dan Generate Jawaban

Kita definisikan template prompt, buat chain menggunakan `load_qa_chain` (style lama),
lalu panggil dengan dokumen yang sudah diambil retriever.
"""

# Mendefinisikan template prompt
prompt_template = """
Jawablah pertanyaan ini dengan se-detail mungkin dari konteks yang diberikan,
pastikan untuk memberikan semua detail, jika jawaban tidak ada dalam
konteks yang diberikan cukup katakan, "jawaban tidak tersedia dalam konteks",
jangan memberikan jawaban yang salah\n\n
Konteks:\n {context}?\n
Pertanyaan: \n{question}\n
Jawaban:
"""

# Membuat prompt
prompt = PromptTemplate(template=prompt_template, input_variables=['context', 'question'])

# Memuat QA chain
model = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", api_key=api_key)
chain = load_qa_chain(model, chain_type="stuff", prompt=prompt)

# Mendapatkan jawaban dari model
response = chain({"input_documents": docs, "question": user_question}, return_only_outputs=True)

# Menampilkan jawaban
print("\nJawaban:")
md(response['output_text'])