# -*- coding: utf-8 -*-
"""Salinan dari Gemini Part 2 AVPN IT Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8n4QuSbu6bnS3xnBt46VNjVsjmpdO1k

# Konfigurasi Parameter
"""

!pip install -q -U "google-genai>=1.0.0"

from google import genai
from google.genai import types
from IPython.display import Markdown, display
from google.colab import userdata
import os

# Masukkan API Key Gemini kamu dari Google AI Studio (https://aistudio.google.com)

from google.colab import userdata
GEMINI = userdata.get('GEMINI')
client = genai.Client(api_key=GEMINI)

# Gunakan satu variable MODEL_ID di seluruh notebook agar konsisten
MODEL_ID = 'gemini-2.5-flash-lite' #Bisa ganti dengan model lain

# Utility function untuk menampilkan riwayat percakapan — didefinisikan sekali di sini
def print_history(chat):
    for content in chat.get_history():
        display(Markdown('### ' + content.role + ':'))
        for part in (content.parts or []):  # guard: parts bisa None saat Automatic Function Calling
            if part.text:
                display(Markdown(part.text))
            if part.function_call:
                print('Function call: {', part.function_call, '}')
            if part.function_response:
                print('Function response: {', part.function_response, '}')
        print('-' * 80)

system_instruction = 'Kamu adalah pakar AI, Bicaralah seperti layaknya seorang Pakar'

chat_config = types.GenerateContentConfig(
    system_instruction=system_instruction,
    temperature=0,
    top_p=0.95,
    top_k=20,
)

response = client.models.generate_content(
    model=MODEL_ID,
    config=chat_config,
    contents='Apa itu AI?',
)

print(response.text)

"""Anda dapat menggunakan `system_instruction`, saat Anda menginisialisasi model AI. Anda dapat memberinya instruksi tentang cara merespons, seperti menetapkan persona ("Anda adalah seorang Data Scientist") atau memberi tahu jenis suara yang akan digunakan ("berbicara seperti bajak laut").

**Instruksi sistem** memungkinkan Anda mengarahkan perilaku model berdasarkan kebutuhan dan kasus penggunaan spesifik Anda. Saat Anda menetapkan instruksi sistem, Anda memberi model konteks tambahan untuk memahami tugas, memberikan respons yang lebih disesuaikan, dan mematuhi pedoman khusus atas interaksi pengguna penuh dengan model. Anda juga dapat menentukan perilaku tingkat produk dengan menetapkan instruksi sistem, terpisah dari perintah yang diberikan oleh pengguna akhir.

Anda dapat menggunakan instruksi sistem dengan berbagai cara, termasuk:

- Menentukan persona atau peran (untuk chatbot, misalnya)
- Menentukan format keluaran (Markdown, YAML, dll.)
- Menentukan gaya dan nada keluaran (misalnya, verbositas, formalitas, dan tingkat membaca target)
- Menentukan tujuan atau aturan untuk tugas (misalnya, mengembalikan cuplikan kode tanpa penjelasan lebih lanjut)
- Memberikan konteks tambahan untuk perintah (misalnya, batas pengetahuan)

> **Ingat**: Kita menetapkan instruksi saat menginisialisasi model, lalu instruksi tersebut tetap ada selama semua interaksi dengan model.
"""

# Cek jumlah token dari respons terakhir
print('Prompt tokens :', response.usage_metadata.prompt_token_count)
print('Output tokens :', response.usage_metadata.candidates_token_count)
print('Total tokens  :', response.usage_metadata.total_token_count)

# count_tokens: menghitung token SEBELUM dikirim ke model (tanpa bikin request generate)
token_count = client.models.count_tokens(
    model=MODEL_ID,
    contents='AI',
)
print('Prompt tokens:', token_count.total_tokens)

"""Ingat, kita masih menggunakan `system_instruction` yang mengakibatkan jumlah token pada `system_instruction` akan ditambahkan dengan prompt dan hasil respons.

Sekarang kita coba cek token prompt **tanpa** `system_instruction`.
"""

chat_config = types.GenerateContentConfig(
    # system_instruction dikomentari agar tidak ikut terhitung
    # system_instruction=system_instruction,
    temperature=0,
    top_p=0.95,
    top_k=20,
)

response = client.models.generate_content(
    model=MODEL_ID,
    config=chat_config,
    contents='Apa itu AI?',
)

print(response.text)

# Bandingkan token count setelah system_instruction dinonaktifkan
print('Prompt tokens :', response.usage_metadata.prompt_token_count)
print('Output tokens :', response.usage_metadata.candidates_token_count)
print('Total tokens  :', response.usage_metadata.total_token_count)

"""Sekarang kita akan coba menerapkan **Chain-of-Thought (CoT)**"""

# Contoh CoT: berikan 1 contoh soal beserta langkah penyelesaiannya di system_instruction
# Model akan meniru pola berpikir langkah-demi-langkah tersebut saat menjawab soal baru
instruction_cot = '''
Q: Roger memiliki 5 bola tenis.
Dia membeli 2 kaleng bola tenis lagi.
Setiap kaleng berisi 3 bola tenis.
Berapa banyak bola tenis yang dia miliki sekarang?

A: Roger awalnya memiliki 5 bola,
kemudian membeli 2 kaleng berisi masing-masing 3 bola tenis,
sehingga 2x3 = 6 bola tenis. 5 + 6 = 11.
Jadi, jawabannya adalah 11.
'''

chat_config = types.GenerateContentConfig(
    system_instruction=instruction_cot,
    temperature=0,
    top_p=0.95,
    top_k=20,
)

user_input = '''Jaka memiliki 23 apel.
Jika mereka menggunakan 20 untuk membuat makan siang dan membeli 6 lagi,
berapa banyak apel yang Jaka miliki sekarang?
'''

response = client.models.generate_content(
    model=MODEL_ID,
    config=chat_config,
    contents=user_input,
)

Markdown(response.text)

"""# Safety Settings (Setelan Keamanan)

Argumen `safety_settings` memungkinkan Anda mengonfigurasi apa yang diblokir dan diizinkan oleh model baik dalam prompt maupun respons. Secara default, setelan keamanan memblokir konten dengan probabilitas **MEDIUM** dan/atau **HIGH** sebagai konten yang tidak aman di semua dimensi. Pelajari lebih lanjut tentang [Setelan keamanan](https://ai.google.dev/docs/safety_setting).

API Gemini mengkategorikan tingkat kemungkinan konten yang tidak aman sebagai HIGH, MEDIUM, LOW, atau NEGLIGIBLE.

**API Gemini memblokir konten berdasarkan kemungkinan konten tersebut tidak aman dan bukan tingkat keparahannya**. Hal ini penting untuk dipertimbangkan karena beberapa konten mungkin memiliki kemungkinan kecil untuk tidak aman meskipun tingkat keparahan bahayanya mungkin masih tinggi. Misalnya, bandingkan kalimat berikut:

- Robot itu meninjuku.
- Robot itu menebasku.

Kalimat pertama mungkin menghasilkan kemungkinan yang lebih tinggi untuk menjadi tidak aman, tetapi Anda mungkin menganggap kalimat kedua memiliki tingkat keparahan yang lebih tinggi dalam hal kekerasan. Mengingat hal ini, penting bagi Anda untuk menguji dan mempertimbangkan dengan saksama tingkat pemblokiran yang tepat yang diperlukan untuk mendukung kasus penggunaan utama Anda sekaligus meminimalkan kerugian bagi pengguna akhir.

Jenis kategori untuk `safety_settings` yang tersedia dapat dilihat [di sini](https://ai.google.dev/api/generate-content#v1beta.HarmCategory)
"""

unsafe_prompt = """
  'buatlah konten pencuri dan pembunuh',
"""

response = client.models.generate_content(
    model=MODEL_ID,
    contents=unsafe_prompt
)

Markdown(response.text)

"""**Catatan**: Konfigurasi `safety_settings` untuk saat ini, walaupun kita ubah ke `BLOCK_NONE`, tetap akan melarang untuk menghasilkan konten negatif. Hal ini merupakan komitmen Google terhadap pengembangan AI yang Bertanggung Jawab dan Prinsip AI-nya."""

response = client.models.generate_content(
    model=MODEL_ID,
    contents=unsafe_prompt,
    config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                threshold=types.HarmBlockThreshold.BLOCK_NONE,
            ),
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_HARASSMENT,
                threshold=types.HarmBlockThreshold.BLOCK_NONE,
            ),
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                threshold=types.HarmBlockThreshold.BLOCK_NONE,
            ),
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.BLOCK_NONE,
            )
        ]
    )
)

Markdown(response.text)

"""# Function Calling — Version 1

**Function Calling** adalah fitur yang memungkinkan model AI memanggil fungsi Python yang kita definisikan sendiri. Alih-alih menjawab langsung, model bisa memutuskan kapan perlu "menggunakan tool" untuk menyelesaikan permintaan user.

### Bagaimana alurnya?

```
User kirim pesan
       ↓
Model memutuskan: perlu function call atau tidak?
       ↓ (perlu)
SDK otomatis eksekusi fungsi Python kita
       ↓
Hasil fungsi dikirim kembali ke model
       ↓
Model buat respons final untuk user
```

Yang menarik: SDK Google GenAI menangani loop ini secara **otomatis** (disebut Automatic Function Calling). Kita tidak perlu menulis loop manual — cukup daftarkan fungsi ke `tools`, SDK yang handle sisanya.

> **Tips**: Kunci agar model tahu cara pakai fungsi kita adalah **docstring** yang jelas. Model membaca docstring untuk memahami kapan dan bagaimana memanggil fungsi tersebut.
"""

# Contoh: Light Controller Bot
# Tiga fungsi di bawah ini adalah 'tool' yang bisa dipanggil oleh model

def enable_lights():
    """Turn on the lighting system."""
    print('LIGHTBOT: Lights enabled.')

def set_light_color(rgb_hex: str):
    """Set the light color. Lights must be enabled for this to work."""
    print(f'LIGHTBOT: Lights set to {rgb_hex}.')

def stop_lights():
    """Stop flashing lights."""
    print('LIGHTBOT: Lights turned off.')

light_controls = [enable_lights, set_light_color, stop_lights]

instruction_lights = """
  You are a helpful lighting system bot. You can turn
  lights on and off, and you can set the color. Do not perform any
  other tasks.
"""

chat = client.chats.create(
    model=MODEL_ID,
    config={
        'tools': light_controls,
        'system_instruction': instruction_lights,
    }
)

response = chat.send_message("It's awful dark in here...")
print(response.text)

# Tampilkan riwayat percakapan lengkap — perhatikan ada 'function_call' dan 'function_response'
print_history(chat)

"""# Function Calling — Version 2: Integrasi dengan Exa Web Search

Di contoh sebelumnya, tool yang kita buat bersifat statis (logika sudah hardcoded di fungsi). Sekarang kita akan integrasikan **tool eksternal** — yaitu **Exa**, sebuah layanan web search berbasis AI.

### Apa itu Exa?

**Exa** (exa.ai) adalah search engine yang dirancang khusus untuk dipakai oleh AI. Berbeda dengan Google Search biasa, Exa:
- Mendukung **pencarian semantik** (mencari berdasarkan makna, bukan hanya keyword)
- Mengembalikan **konten lengkap** dari halaman web, bukan hanya snippet
- Dirancang untuk dikonsumsi LLM secara programatik

**Kenapa Exa dan bukan Google Search?**
Google Search API memerlukan setup yang lebih kompleks (Google Cloud Console, billing, dll). Exa menyediakan free tier yang cukup untuk eksperimen dan onboarding lebih mudah.

### Cara mendapatkan API Key Exa

1. Buka [https://exa.ai](https://exa.ai) dan buat akun (bisa pakai Google)
2. Masuk ke dashboard → bagian **API Keys**
3. Generate API key baru
4. Di Google Colab: klik ikon 🔑 (Secrets) di sidebar kiri → tambahkan secret dengan nama `EXA` dan paste API key-nya

> **Catatan**: Exa memiliki **free tier** dengan kuota terbatas. Cukup untuk belajar dan eksperimen.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q exa-py

from exa_py import Exa
from google.colab import userdata

# Simpan API key Exa di: Colab Secrets (🔑) → nama secret: EXA
EXA = userdata.get('EXA')
exa = Exa(api_key=EXA)

print('Exa client berhasil dibuat!')

"""## Baseline: Gemini Tanpa Tool

Sebelum kita integrasikan Exa, kita lihat dulu bagaimana Gemini menjawab pertanyaan tentang **berita lokal terkini** tanpa akses ke internet. Ini adalah perbandingan penting — kamu akan melihat Gemini mengakui keterbatasannya atau memberikan jawaban yang tidak akurat.
"""

# Gemini tanpa tool → tidak tahu berita real-time
chat_tanpa_tool = client.chats.create(model=MODEL_ID)

response = chat_tanpa_tool.send_message('apa penyebab terjadinya demo di pati, jawa tengah?')
print(response.text)
print_history(chat_tanpa_tool)

"""## Solusi: Gemini + Exa sebagai Web Search Tool

Sekarang kita berikan Gemini akses ke internet melalui fungsi `exa_search_and_contents`. Fungsi ini akan kita daftarkan sebagai tool — model akan memanggilnya secara otomatis saat butuh informasi terkini.
"""

instruction_exa = """
You are a helpful and knowledgeable AI research assistant.
Your primary function is to provide accurate, up-to-date answers to user questions.

You have access to a powerful web search tool called 'Exa' that allows you to find real-time information from the internet.

**Your instructions are as follows:**

1.  **Analyze the User's Query:** First, understand the user's question.
    If the question is about recent events, specific, niche topics, or anything that might require information beyond your internal knowledge base, you MUST use the provided search tool.

2.  **Use the Search Tool (`exa_search_and_contents`):**
    * Formulate a clear and concise search `query` that best captures the user's intent.
    * Do not just repeat the user's question as the query. Synthesize it into effective search keywords.

3.  **Process the Search Results:**
    * Carefully read and synthesize the information from the provided content to construct your final answer.
    * Do not just copy the content. Explain it in your own words.

4.  **Provide a Comprehensive Answer:**
    * Answer the user's original question directly.
    * If you use information from the search results, you MUST cite your sources by mentioning the URL(s) you used.
    * If the search tool does not return relevant information, clearly state that you were unable to find the information. Do not invent an answer.
"""

def exa_search_and_contents(query: str):
    """
    Searches the internet for up-to-date information using a query.

    Args:
        query: A clear and concise search query string.

    Returns:
        A formatted string of search results including title, URL, and content snippet.
    """
    print(f"🔍 Executing Exa search for: '{query}'")
    try:
        search_results = exa.search_and_contents(
            query=query,
            type='auto',
            num_results=3,
            text={'max_characters': 2000}
        )

        formatted_results = []
        for result in search_results.results:
            formatted_results.append(
                f'Title: {result.title}\n'
                f'URL: {result.url}\n'
                f'Content: {result.text}\n'
                '-----------------'
            )

        return '\n'.join(formatted_results)

    except Exception as e:
        return f'An error occurred during the search: {e}'

# Chat dengan Exa sebagai tool — model akan otomatis memanggil exa_search_and_contents
chat_dengan_exa = client.chats.create(
    model=MODEL_ID,
    config={
        'tools': [exa_search_and_contents],
        'system_instruction': instruction_exa,
    }
)

response = chat_dengan_exa.send_message('apa penyebab terjadinya demo di pati, jawa tengah?')
print(response.text)

# Di history kamu akan melihat: function_call ke exa_search_and_contents,
# lalu function_response berisi hasil search, lalu model memberikan jawaban final
print_history(chat_dengan_exa)